#! /usr/bin/awk -f

func lprint ()
{
	if (line) {
		gsub("\\\\    ", "", line)
		print line
		line = ""
	}
}

BEGIN {
	while (getline) {
		if ($0 ~ /^[\t ]*#/) {
			continue
		}
		if ($0 ~ "^/") {
			lprint()
			cmd = $0 " "
			continue
		}
		if ($0 ~ "^ ") {
			sscmd = $0
			line = line sscmd
			continue
		} else {
			lprint()
			scmd = $0
			line = cmd scmd
			continue
		}
	}
	lprint()
}
