#! /usr/bin/awk -f

# line is a comment
/^#/ {
	print;
	next;
}

# line is a ROS command path
/^\// {
	cmdpath = $0;
	next;
}

# line is a (potentially partial) ROS command
{
	# strip line of ...
	sub(/^ +/, ""); # leading spaces and ...
	to_be_continued = sub(/\\$/, ""); # ...trailing backspace, if any

	# append stripped line to buffer
	cmd = cmd $0;

	if (!to_be_continued) {
		# print (absolute) command
		print cmdpath " " cmd;
		cmd = "";
	}
}
