#! /bin/sh

orig=$(dirname $0)
arg=$1
file=-

if [ -n "$arg" ]; then
	if [ ! -f "$arg" ]; then
		arg=$orig/rsc/$arg
	fi
	if [ ! -f "$arg" ]; then
		exit
	fi
	file=$arg
fi

exec awk '{
	line = $0
	while (match(line, /\$\{[^}]+\}/)) {
		 beg = substr(line, 1, RSTART-1)
		 var = substr(line, RSTART, RLENGTH)
		line = substr(line, RSTART+RLENGTH)
		printf("%s", beg)
		system("sh -c '\''printf \""var"\"'\''")
	}
	print line
}' "$file"
